#cloud-config
package_upgrade: true

packages:
  - nano
  - wget
  - unzip

runcmd:
  - wget https://www.vpubchain.info/files/masternode.sh
  - chmod +x masternode.sh
  - ./masternode.sh 5KH11kxNhR2G6MhdohbH1DdKMnL8745VFXvPvUDoYqAdN5dDF7L -y